name: Update Submodules

on:
  push:
    branches: [ main ]  # or your default branch name
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update submodules
      run: |
        git submodule update --init --recursive --force
        git submodule update --recursive --remote --force
    
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update submodules" || echo "No changes to commit"
        git push
